root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/control-plane ."
  bin = "./tmp/control-plane"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "frontend"]
  delay = 1000

[misc]
  clean_on_exit = true
